export const banners = [
  {
    id: 1,
    title: 'Download Our Mobile App',
    description: 'Get the Tape mobile app for iOS and Android.',
    type: 'Promotion',
    views: '12,450',
    clicks: '1,856',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Active',
  },
  {
    id: 2,
    title: 'New Feature: Advanced Analytics',
    description: 'Check out our new advanced analytics dashboard',
    type: 'Announcement',
    views: '39',
    clicks: '-',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Ended',
  },
  {
    id: 3,
    title: 'How do I reset my password?',
    description: 'Check out our new advanced analytics dashboard',
    type: 'Promotion',
    views: '21',
    clicks: '-',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Paused',
  },
  {
    id: 4,
    title: 'How do I reset my password?',
    description: 'To reset your password, click on "Forgot Password" on the login page and follow the instructions sent to your email.',
    type: 'Warning',
    views: '37',
    clicks: '-',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Draft',
  },
  {
    id: 5,
    title: 'How do I reset my password?',
    description: 'To reset your password, click on "Forgot Password" on the login page and follow the instructions sent to your email.',
    type: 'Published',
    views: '6',
    clicks: '-',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Active',
  },
  {
    id: 6,
    title: 'How do I reset my password?',
    description: 'To reset your password, click on "Forgot Password" on the login page and follow the instructions sent to your email.',
    type: 'Draft',
    views: '16',
    clicks: '-',
    ctr: '14%',
    startDate: '2026-01-19',
    endDate: '2026-02-21',
    duration: '33 days',
    status: 'Draft',
  },
];
